### ISSUE TITLE
Question about the calculation.

### ISSUE THREAD

**Issue by RunxinXu** [bloodwass/mixout#5]
Hi, great job!
I have a little question about the following calculation.

>  [(1 - Bernoulli(1 - p) mask) * target + (Bernoulli(1 - p) mask) * input - p * target]/(1 - p) 

What do you mean by [ - p * target ] ?
Is it something like rescale? Could you offer some explanations :) Thanks~

**Comment by bloodwass** [comment]
Hi,

Yes, you're right.

It is a rescale technique.

This line makes the expectation of the mixed parameters,
 
`E[(1 - Bernoulli(1-p)) * target + Bernoulli(1-p) * input] = p*target + (1-p)*input`,

be full parameters, input.

Due to this trick, we can avoid the additional calculation of mixout when testing. 

Please see [inverted dropout](https://github.com/pytorch/pytorch/blob/ceb4f84d12304d03a6a46693e54390869c0c208e/torch/nn/_functions/dropout.py#L33).

Best,
Cheolhyoung

**Comment by RunxinXu** [comment]
ok, I got it! Thanks:)
